-- SQL Schema for German Quiz Master (Supabase)

-- 1. Create 'users' table (Public Profiles)
create table public.users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  auth_id uuid references auth.users(id), -- Link to Supabase Auth User
  email text unique not null,
  name text,
  surname text,
  role text default 'user',
  accessB1 integer default 0,
  accessB2 integer default 0,
  isActive integer default 0,
  deviceLimit integer default 1,
  phone text
);

-- 2. Create 'settings' table (For Maintenance Mode, etc.)
create table public.settings (
  key text primary key,
  value text
);

-- Insert default maintenance mode setting
insert into public.settings (key, value) values ('maintenance_mode', 'false');


-- 3. Enable Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.settings enable row level security;

-- 4. Policies

-- Policy: Allow users to read their own profile
create policy "Users can view own profile"
on public.users for select
using ( auth.uid() = auth_id );

-- Policy: Allow Admins to read all profiles
-- Note: Requires checking the role. Since we store role in this table, we might get infinite recursion if we select from it in the policy.
-- A better way is to use Custom Claims, but for simplicity:
-- We will allow read access to everyone for now (or at least authenticated users), 
-- OR strictly:
create policy "Admins can view all profiles"
on public.users for select
using ( 
  auth.uid() in (
    select auth_id from public.users where role = 'admin'
  )
);

-- Policy: Allow Insert (Registration) - Allow authenticated or anon?
-- Since we do insert after signUp, the user is authenticated.
create policy "Users can insert their own profile"
on public.users for insert
with check ( auth.uid() = auth_id );

-- Policy: Admins can update/delete users
create policy "Admins can update users"
on public.users for update
using ( 
  auth.uid() in (
    select auth_id from public.users where role = 'admin'
  )
);

create policy "Admins can delete users"
on public.users for delete
using ( 
  auth.uid() in (
    select auth_id from public.users where role = 'admin'
  )
);

-- Settings Policies
create policy "Everyone can view settings"
on public.settings for select
using ( true );

create policy "Admins can update settings"
on public.settings for update
using ( 
  auth.uid() in (
    select auth_id from public.users where role = 'admin'
  )
);

-- 5. Create the first Admin (IMPORTANT: Run this AFTER signing up as the first user)
-- Example:
-- update public.users set role = 'admin', isActive = 1, accessB1 = 1, accessB2 = 1 where email = 'YOUR_ADMIN_EMAIL';

