<?php
/**
 * Quiz Name Mappings
 * Maps quiz file numbers to their display names
 */

return [
    // B1 Lesen Teil 1
    '204.html' => 'PETRA/JENNIFER',
    '206.html' => 'EVA/IRIS',
    '215.html' => 'SOPHIE/ANDREAS2',
    '219.html' => 'NADJA/CLAUDIA',
    '221.html' => 'NICOLE',
    '223.html' => 'ANDREAS',
    '226.html' => 'ANNIKA1',
    '227.html' => 'ANNIKA2/SONJA<br>CORINA',
    '228.html' => 'CAROLINA/ALICIA',
    '230.html' => 'VERA',
    '232.html' => 'THOMAS',
    '234.html' => 'TAMARA/JAKOB<br>PAUL',
    '235.html' => 'JAN',
    '237.html' => 'VIKTOR',
    '240.html' => 'ALEX & CORA',
    '242.html' => 'RITA',
    '244.html' => 'MIROSLAV',
    '246.html' => 'KARLA',
    '247.html' => 'MORITZ',
    
    // B1 Lesen Teil 2
    '205.html' => 'Petra & ALICIA',
    '207.html' => 'EVA1',
    '208.html' => 'IRIS',
    '216.html' => 'SOPHIE',
    '220.html' => 'NADJA & CLAUDIA',
    '222.html' => 'NICOLE',
    '224.html' => 'ANDREAS',
    '225.html' => 'ANDREAS2 & CORINA<br>ANNIKA(1&2)',
    '229.html' => 'CAROLINA/VERA',
    '231.html' => 'JENNIFER & TAMARA<br>JAKOB/PAUL',
    '233.html' => 'THOMAS',
    '236.html' => 'JAN',
    '238.html' => 'VIKTOR',
    '239.html' => 'SONJA',
    '241.html' => 'ALEX & CORA',
    '243.html' => 'RITA',
    '245.html' => 'MIROSLAV & KARLA',
    '248.html' => 'MORITZ',
    '249.html' => 'MARA',
    
    // B1 Lesen Teil 3
    '201.html' => 'Petra',
    '203.html' => 'EVA1',
    '202.html' => 'IRIS',
    '217.html' => 'SOPHIE',
    '218.html' => 'NADJA & CLAUDIA',
    '286.html' => 'ANDREAS1',
    '287.html' => 'ANDREAS2',
    '288.html' => 'CAROLINA',
    
    // B1 Sprachbausteine Teil 1
    '209.html' => 'PETRA/NADJA2<br>CLAUDIA',
    '211.html' => 'EVA',
    '213.html' => 'IRIS',
    '250.html' => 'SOPHIE',
    '251.html' => 'NICOLE',
    '254.html' => 'ANDREAS',
    '257.html' => 'ANDREAS2/VIKTOR<br>SONJA',
    '259.html' => 'ANNIKA1',
    '261.html' => 'ANNIKA2/JAN<br>CORINA',
    '262.html' => 'CAROLINA/RITA',
    '264.html' => 'VERA/PAUL',
    '266.html' => 'THOMAS/ANNA',
    '268.html' => 'JENNIFER',
    '269.html' => 'TAMARA/JAKOB',
    '273.html' => 'ALEX & CORA',
    '278.html' => 'MIROSLAV',
    '280.html' => 'KARLA',
    '282.html' => 'MORITZ',
    '283.html' => 'ALICIA',
    
    // B1 Sprachbausteine Teil 2
    '210.html' => 'PETRA/ALICIA',
    '212.html' => 'EVA',
    '214.html' => 'IRIS',
    '253.html' => 'SOPHIE',
    '252.html' => 'NICOLE',
    '255.html' => 'NADJA/CLAUDIA',
    '256.html' => 'ANDREAS',
    '258.html' => 'ANDREAS2/JAN',
    '260.html' => 'ANNIKA1&2',
    '263.html' => 'CAROLINA/CORINA',
    '265.html' => 'VERA',
    '267.html' => 'THOMAS/ANNA<br>JENNIFER',
    '270.html' => 'TAMARA/JAKOB<br>SONJA',
    '272.html' => 'VIKTOR',
    '274.html' => 'ALEX & CORA',
    '276.html' => 'PAUL',
    '277.html' => 'RITA',
    '279.html' => 'MIROSLAV',
    '281.html' => 'KARLA/MORITZ',
    '284.html' => 'JAKOB2',
    
    // B1 Hören
    '271.html' => 'Teil 1',
    '285.html' => 'Teil 2',
    '275.html' => 'Teil 3',
    
    // B2 Lesen Teil 1
    '11.html' => 'Umwelt',
    '12.html' => 'Impfung',
    '16.html' => 'Kinderhandy',
    '17.html' => 'Drogen',
    '18.html' => 'Tanzkurs',
    '25.html' => 'Limonade',
    '26.html' => 'Grundschule',
    '27.html' => 'Insekten',
    '28.html' => 'Österreich',
    '39.html' => 'Jugend forscht',
    '40.html' => 'Sport ist Gesund',
    '41.html' => 'Inseln',
    '42.html' => 'In den Alpen',
    '143.html' => 'In den Alpen 2',
    '43.html' => 'Kartoffel',
    '59.html' => 'Bilder',
    '70.html' => 'Licht',
    '71.html' => 'Spielen',
    '72.html' => 'Programmieren',
    '73.html' => 'Trampoline',
    '74.html' => 'Benzin',
    '64.html' => 'Kaffee',
    '84.html' => 'Bonbons',
    '86.html' => 'Geld',
    '85.html' => 'Auf dem Weg',
    '98.html' => 'Schlafzug',
    '101.html' => 'Keine Zeit',
    '136.html' => 'Licht (NEUE)',
    
    // B2 Lesen Teil 2
    '4.html' => 'Puppenmacher',
    '5.html' => 'Österreich',
    '6.html' => 'Parkuhren',
    '7.html' => 'Traumfrau',
    '13.html' => 'Kaufentscheidungen',
    '15.html' => 'Millionäre',
    '19.html' => 'Gehirn',
    '20.html' => 'Verpackungen',
    '21.html' => 'Kreditkarten',
    '22.html' => 'Krista die Kühe',
    '23.html' => 'Ernährung',
    '24.html' => 'Kaffee',
    '134.html' => 'Kaffee 2',
    '29.html' => 'Großraumbüros',
    '44.html' => 'Familie',
    '45.html' => 'Babys',
    '46.html' => 'Karneval von Unna',
    '47.html' => 'Mehrsprachige',
    '60.html' => 'Gesundes Essen',
    '61.html' => 'Dienstmädchen',
    '75.html' => 'Reitergruppe',
    '77.html' => 'Brigitte Vollmer',
    '79.html' => 'Nachtzug',
    '102.html' => 'Die ganze Welt',
    '123.html' => 'Kellner',
    '131.html' => 'Weniger Euro',
    
    // B2 Lesen Teil 3
    '62.html' => 'Fernsehprogramm',
    '63.html' => 'Sport ist Gesund',
    '65.html' => 'Kellner',
    '66.html' => 'Schwägerin',
    '145.html' => 'Schwägerin(das)',
    '67.html' => 'Dokumentarfilm',
    '68.html' => 'Wein und Insekten',
    '69.html' => 'Grundschule',
    '141.html' => 'Kein Zeit',
    '76.html' => 'Kein Zeit 2',
    '78.html' => 'Sport',
    '80.html' => 'Gärten',
    '81.html' => 'Apotheker',
    '82.html' => 'Urlaub',
    '83.html' => 'Anwalt',
    '87.html' => 'Der Hund',
    '88.html' => 'Musik',
    '89.html' => 'Haushalt',
    '90.html' => 'Musikinstrumente',
    '108.html' => 'Schiffsreise',
    '109.html' => 'Ausflug',
    '110.html' => 'Schwägerin Gesund',
    '111.html' => 'Übersetzerin',
    '124.html' => 'Tierdokumentationen',
    '132.html' => 'Schlafzug',
    '140.html' => 'Bonbons',
    
    // B2 Sprachbausteine Teil 1
    '30.html' => 'Herr Martini',
    '31.html' => 'Judith oder Lina',
    '32.html' => 'Igor',
    '33.html' => 'Maria',
    '34.html' => 'Ida',
    '35.html' => 'Andrea',
    '91.html' => 'Andrea 2',
    '36.html' => 'Autorinnen und Autoren',
    '37.html' => 'Geissler oder Dippold',
    '38.html' => 'Herr Dr. Dobromil',
    '92.html' => 'Frau Szabo',
    '144.html' => 'Frau Szabo 2',
    '93.html' => 'Corinna',
    '94.html' => 'Justus oder Juhannas',
    '95.html' => 'Justus oder Juhannas 2',
    '96.html' => 'Ferdinand, Phillip, Christopher',
    '97.html' => 'Liebe Paola',
    '100.html' => 'Liebe Julian',
    '103.html' => 'Liebe Lara',
    '105.html' => 'Lieber David',
    '106.html' => 'Liebe Maria, Lieber Timur',
    '114.html' => 'Liebe Vanessa',
    '115.html' => 'Frau Goronsksa',
    '118.html' => 'Liebe Karin',
    '119.html' => 'Liebe Jutta',
    '126.html' => 'Liebe Meike',
    '128.html' => 'Liebe Leon',
    '130.html' => 'Liebe Clara',
    '133.html' => 'Lieber Thomas',
    '135.html' => 'Dr. Moosberger',
    '137.html' => 'Lina & Florian',
    '138.html' => 'Liebe Agnieszka',
    '142.html' => 'Jens',
    
    // B2 Sprachbausteine Teil 2
    '1.html' => 'Theater für Kinder und Jugendliche',
    '2.html' => 'Im Restaurant',
    '3.html' => 'Das Fahrrad: ernsthafte Konkurrenz fürs Auto?',
    '14.html' => 'Haustieren',
    '48.html' => 'Liebesgrüße aus der Kühltruhe',
    '49.html' => 'Braunbären',
    '50.html' => 'Ausbildung',
    '51.html' => 'Skipiste',
    '52.html' => 'Jugend diskutiert',
    '53.html' => 'Manipulierte Bilder',
    '54.html' => 'Haustieren',
    '55.html' => 'Schwarzarbeit',
    '56.html' => 'Handschrift',
    '57.html' => 'Schulweg',
    '58.html' => 'Höflichkeit',
    '99.html' => 'Obst und Gemüse',
    '104.html' => 'TV-Bilder',
    '107.html' => 'Freund des Menschen',
    '112.html' => 'BIO',
    '113.html' => 'Erfolg',
    '116.html' => 'Deutschland',
    '117.html' => 'Joggen',
    '120.html' => 'Maßgeschneidert',
    '121.html' => 'Der Hund',
    '122.html' => 'Online—Sprachkurse',
    '125.html' => 'Fische',
    '127.html' => 'Man(n) kocht selbst',
    '129.html' => 'Schönschrift',
    '139.html' => 'Kaffee und Kuchen',
    
    // B2 Hören
    '8.html' => 'Teil 1',
    '9.html' => 'Teil 2',
    '10.html' => 'Teil 3',
];

